"""Change length of bookmarks #2

Revision ID: 06ca56f6ce37
Revises: cd541adca045
Create Date: 2018-12-18 14:30:54.071180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ca56f6ce37'
down_revision = 'cd541adca045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_bookmark_url'), 'bookmark', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmark_url'), table_name='bookmark')
    op.drop_column('bookmark', 'url')
    # ### end Alembic commands ###
