"""Change length of bookmarks #4

Revision ID: 17f11a285f85
Revises: 27a51010f13c
Create Date: 2018-12-18 14:33:19.682919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f11a285f85'
down_revision = '27a51010f13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('url', sa.String(length=190), nullable=True))
    op.create_index(op.f('ix_bookmark_url'), 'bookmark', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmark_url'), table_name='bookmark')
    op.drop_column('bookmark', 'url')
    # ### end Alembic commands ###
