"""Bookmark User Relationship and optional field

Revision ID: 56d37c48fd9c
Revises: dd790f425d0c
Create Date: 2019-01-09 17:22:23.175554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d37c48fd9c'
down_revision = 'dd790f425d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###
