"""Bookmarks table

Revision ID: 9bfc10fdf5d0
Revises: 7b19eac39ef2
Create Date: 2018-12-10 17:59:41.299112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfc10fdf5d0'
down_revision = '7b19eac39ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2083), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmark_timestamp'), 'bookmark', ['timestamp'], unique=False)
    op.create_index(op.f('ix_bookmark_url'), 'bookmark', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmark_url'), table_name='bookmark')
    op.drop_index(op.f('ix_bookmark_timestamp'), table_name='bookmark')
    op.drop_table('bookmark')
    # ### end Alembic commands ###
