"""Change length of bookmarks #1

Revision ID: cd541adca045
Revises: 373997d87eaa
Create Date: 2018-12-18 14:30:19.921818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd541adca045'
down_revision = '373997d87eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookmark_url', table_name='bookmark')
    op.drop_column('bookmark', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('url', mysql.VARCHAR(collation='utf8_unicode_ci', length=2083), nullable=True))
    op.create_index('ix_bookmark_url', 'bookmark', ['url'], unique=False)
    # ### end Alembic commands ###
